// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "dba1bdf5-9e97-4dac-97dc-43afb9f78777");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.background-update-timer", 0);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 0);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1544035648);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 0);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 0);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 0);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 0);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1544035581);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 76);
user_pref("browser.newtabpage.activity-stream.impressionId", "{229be823-d547-4ab2-9b96-0d794f45957d}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1543960800);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 3);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"webcompat-reporter_mozilla_org\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1544035674905");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1544037491905");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1544035636211");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1544039236211");
user_pref("browser.search.region", "ZA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20181108141956");
user_pref("browser.shell.checkDefaultBrowser", false);
user_pref("browser.shell.mostRecentDateSetAsDefault", "1544035618");
user_pref("browser.slowStartup.averageTime", 2222);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20181108141956");
user_pref("browser.startup.homepage_override.mstone", "64.0");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[],\"currentVersion\":15,\"newElementCount\":0}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 3);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1544035590978");
user_pref("devtools.chrome.enabled", true);
user_pref("devtools.debugger.prompt-connection", false);
user_pref("devtools.debugger.remote-enabled", true);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.iniFile.exists.appversion", "64.0");
user_pref("distribution.iniFile.exists.value", false);
user_pref("dom.push.userAgentID", "b62e8eb648794dba863bc119490d3614");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 27);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20181108141956");
user_pref("extensions.lastAppVersion", "64.0");
user_pref("extensions.lastPlatformVersion", "64.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"51161474-1b98-4402-9a5b-83d31dc2efba\",\"screenshots@mozilla.org\":\"0abbb35d-8f9b-45ff-93dd-51aa0f534f71\",\"webcompat-reporter@mozilla.org\":\"a2107a5c-d96b-45d9-a2a3-2b0245699947\",\"webcompat@mozilla.org\":\"32b28c41-73f7-4e6e-a0c3-eb7f09791891\"}");
user_pref("layers.mlgpu.sanity-test-failed", false);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-msvc-x64");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1544035654);
user_pref("media.gmp-gmpopenh264.version", "1.7.1");
user_pref("media.gmp-manager.buildID", "20181108141956");
user_pref("media.gmp-manager.lastCheck", 1544035647);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("media.hardware-video-decoding.failed", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("sanity-test.advanced-layers", true);
user_pref("sanity-test.device-id", "0x1244");
user_pref("sanity-test.driver-version", "23.21.13.8813");
user_pref("sanity-test.running", false);
user_pref("sanity-test.version", "20181108141956");
user_pref("security.sandbox.content.tempDirSuffix", "{855de609-5c3e-4eb3-9024-7c7473047035}");
user_pref("security.sandbox.plugin.tempDirSuffix", "{a6d36c33-c83a-4d77-b03f-80fac0b576bc}");
user_pref("services.blocklist.addons.checked", 1544035592);
user_pref("services.blocklist.gfx.checked", 1544035592);
user_pref("services.blocklist.onecrl.checked", 1544035592);
user_pref("services.blocklist.pinning.checked", 1544035592);
user_pref("services.blocklist.plugins.checked", 1544035592);
user_pref("services.settings.clock_skew_seconds", 60);
user_pref("services.settings.last_etag", "\"1544035467383\"");
user_pref("services.settings.last_update_seconds", 1544035592);
user_pref("services.settings.main.language-dictionaries.last_check", 1544035592);
user_pref("services.settings.main.onboarding.last_check", 1544035592);
user_pref("services.settings.main.sites-classification.last_check", 1544035592);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1544035617);
user_pref("toolkit.telemetry.cachedClientID", "09bb3bf2-890d-4963-af35-4030f0e1223d");
user_pref("toolkit.telemetry.previousBuildID", "20181108141956");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("ui.osk.debug.keyboardDisplayReason", "IKPOS: Touch screen not found.");
